version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./app/DB/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: users
    ports:
      - "5432:5432"
  app:
    image: gnshjoo/flask
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db