version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - /Users/gnshjoo/TEST_HOME:/var/lib/postgresql
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: users
    ports:
      - "5432:5432"